### ISSUE TITLE
How many phone number checks can i do on one session before getting banned

### ISSUE THREAD

**Issue by sudoranger** [allburov/whatsapp-http-api#136]
Hey im building a database for an app that allows people to reconnect with relatives
my question is how many checks per day or per hour can i do before getting a session banned and how can i mitigate my session getting banned

**Comment by arthurbarros** [comment]
There is no limit on waha ends. This is more related to how WhatsApp API deals with it. I suggest you to get a single number to burn it and figure it out by yourself.

What I've learned so far is. If you just talk to numbers that talked with you first, it's really hard to get banned. otherwise it can happen instantly

**Comment by allburov** [comment]
As @arthurbarros answered - the best way is to try doing that until you get banned :) 
@arthurbarros thank you for the answer! 

@sudoranger if you're using more than one session - consider set up proxies for each one, so all check requests don't go from a single place to WhatsApp servers https://waha.devlike.pro/docs/how-to/config/#proxy
