### ISSUE TITLE
Session remains in "WORKING" state even if I disconnect it from phone.

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#137]
Hello,

When I disconnect whatsapp web from my phone then also session remains in "WORKING" state when I make a /sessions call.
If I call /screenshot end point then it fails saying session is closed. but still /sessions call returns "WORKING" state.

Here is sample response `/sessions`

```
[
  {
    "name": "4004",
    "status": "WORKING",
    "config": {
      "proxy": null,
      "webhooks": [
        {
          "url": "https://820a-116-74-114-254.ngrok-free.app/api/whatsapi/whatsapp/webhook",
          "events": [
            "message",
            "message.any",
            "message.ack"
          ],
          "hmac": null,
          "retries": null,
          "customHeaders": null
        }
      ]
    }
  }
]
```

Here is sample response of '/screenshot' end point.

```

  "statusCode": 500,
  "timestamp": "2023-07-12T10:00:45.551Z",
  "exception": {
    "stack": "Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.\n    at CDPSession.send (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)\n    at Page._screenshotTask (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1984:28)\n    at /app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1981:62",
    "message": "Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.",
    "name": "Error"
  },
  "request": {
    "path": "/api/screenshot?session=4004",
    "method": "GET",
    "body": {},
    "query": {
      "session": "4004"
    }
  },
  "version": {
    "version": "2023.7.5",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

Please fix this status issue.

**Comment by khushboo-scogo** [comment]
@ehussain   hey, I have been using waha and getting this same issue. Have you figured out any solution to this?

**Comment by gr8tushar** [comment]
I am also facing the same issue. 
As a work around for now, if I get an exception like that, I consider the status STOP/ CLOSED.

**Comment by khushboo-scogo** [comment]
> I am also facing the same issue. As a work around for now, if I get an exception like that, I consider the status STOP/ CLOSED.

yeah, I did something similar for now.

**Comment by allburov** [comment]
Hello! Starting from `2023.10.15`, there have been some changes. These changes are currently available in the Plus version and will be released in the Core version at a later date.

As a result of these changes, sessions with certain statuses will now be marked as "FAILED." Additionally, a new webhook event called `session.status` has been added. This event will provide faster updates in cases where something goes wrong in the system or when a session gets authorized.

https://waha.devlike.pro/docs/how-to/webhooks/#sessionstatus

----
### session.status
The `session.status` event is triggered when the session status changes.
- `STOPPED` - session is stopped
- `STARTING` - session is starting
- `SCAN_QR_CODE` - session is required to scan QR code or login via phone number
- `WORKING` - session is working and ready to use
- `FAILED` - session is failed due to some error. It's likely that authorization is required again or device has been disconnected from that account.
Try to restart the session and if it doesn't help - logout and start the session again.

```json
{
    "event": "session.status",
    "session": "default",
    "me": {
        "id": "7911111@c.us",
        "pushName": "~"
    },
    "payload": {
        "status": "WORKING"
    },
    "engine": "WEBJS",
    "environment": {
        "version": "2023.10.12",
        "engine": "WEBJS",
        "tier": "PLUS"
    }
}
```
