### ISSUE TITLE
Running session with blank space

### ISSUE THREAD

**Issue by ghost** [allburov/whatsapp-http-api#142]
I was requesting if it could be possible to allow session names containing spaces to run successfully.
Example:
{
"name": "Joshua ",
}
this session will not run because it has a space at the end. The session status will not change to SCAN_QR_CODE.

But this session will run successfully because it has no space
{
"name": "Joshua",
}

Please advise if it is possible to implement that.
Thanks

**Comment by allburov** [comment]
Right now it gives `Invalid clientId. Only alphanumeric characters, underscores and hyphens are allowed.`
It happens only with WEBJS engine tho, NOWEB accepts all characters as I can see.

**It's easier to replace all spaces with either hyphens or underscore on your side.**

We could replace it on our side, but later you'll have to encode those characters as well in endpoints like `POST /api/{session}/presence` and others that include session name in the path.
The problem with doing it on our side - these session would be the same for us : `Joshua `, `Joshua%`, `Jushua-`, because all of them would map to `Jushua-`. So you'll have to know mapping rules of the "slugify" algorithm we're using. The less implicit mapping happens in API - the better it's for users, I think.

So my decision is to keep restricting not valid names and don't allow to put there invalid symbols AND to add those validation rules to NOWEB engine later, so we can have consistency across engines

Thank you for your feedback anyway!
