### ISSUE TITLE
Disconnecting  device from whatsapp when POST /logout

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#148]
### Discussed in https://github.com/devlikeapro/whatsapp-http-api/discussions/147

<div type='discussions-op-text'>

<sup>Originally posted by **JoshuaMwamlanda** July 20, 2023</sup>
When I end a session, why doesn't WAHA automatically disconnect my device from WhatsApp?
It only shows I'm inactive but it doesn't disconnect the device in WhatsApp.
I would greatly appreciate any help.

Thanks
</div>

**Comment by devlikepro** [comment]
One more PLUS patron mentioned this https://github.com/devlikeapro/whatsapp-http-api/issues/327

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Fixed in `2024.10.9`

When a session in `WORKING` status on `POST /api/sessions/{NAME}/logout`  request it'll try to remove the device from **Connected Devices** list in the app.

https://waha.devlike.pro/docs/how-to/sessions/#logout-session

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
