### ISSUE TITLE
[feature] message delete webhook events not received

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#190]
Hello,

We would like to receive 'message.delete' ack event when someone deletes a message from their whatsapp phone.
Event is important for us to know if sent message was deleted by user, and our system should get the webhook and should get updated of such actions.

**Comment by allburov** [comment]
@ehussain hi!
just to make sure it doesn't work - you mentioned here https://github.com/devlikeapro/whatsapp-http-api/issues/209

>We receive a delete webhook for messages sent by client (any incoming message)

Does it mean that `message.any` covers `message.delete` event case? Or I misunderstood it...

**Comment by ehussain** [comment]
Hello @allburov .

I tested this morning only, we have subscribed to 'message.any' event but still we are not receiving any webhook for delete case. It seems I mistakenly wrote about delete webhook. 

So as per my understanding and testing. I can say that neither 'delete' api is available nor we are receiving the delete webhook for any messages which is deleted by client.

**Comment by allburov** [comment]
Added new `message.revoked` event in `2023.10.12` (Plus yet)

----

### message.revoked
The `message.revoked` event is triggered when a user, whether it be you or any other participant,
revokes a previously sent message.

```json
{
  "event": "message.ack",
  "session": "default",
  "payload": {
    "before": {
      "id": "some-id-here",
      "timestamp": "some-timestamp-here",
      "body": "Hi there!"
    },
    "after": {
      "id": "some-id-here",
      "timestamp": "some-timestamp-here",
      "body": ""
    }
  }
}
```

**Important notes**:
1. The above messages' ids don't match any of the ids you'll receive in the `message` event, it's a different id.
2. In order to find the message that was revoked, you'll need to search for the message with
   the same timestamp and chat id as the one in the `after` object.
3. `before` field can be null in some cases.
