### ISSUE TITLE
the logout route and the stop?logout=logout route NOWEB

### ISSUE THREAD

**Issue by rafaWPP** [allburov/whatsapp-http-api#211]
the logout route and the stop?logout=logout route
it is not disconnecting
it just shows that it is not connected but if I send a message it will send
so these routes are not working
using NOWEB

**Comment by devlikepro** [comment]
Fixed in `2024.10.9`

When a session in `WORKING` status on `POST /api/sessions/{NAME}/logout`  request it'll try to remove the device from **Connected Devices** list in the app.

https://waha.devlike.pro/docs/how-to/sessions/#logout-session

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
