### ISSUE TITLE
Send image in HD

### ISSUE THREAD

**Issue by giljlle** [allburov/whatsapp-http-api#269]
I’m not sure if there is already a command or feature, but I need to send an image enabling the HD function on WhatsApp, where the image is sent in higher resolution. I appreciate anyone who can help me.
Tks

**Comment by allburov** [comment]
Hi! You need to use `POST /api/sendFile` instead of `POST /api/sendImage`.
https://waha.devlike.pro/docs/how-to/send-messages/#send-file-imagesversionspluspng

Even the official WhatsApp apps don't allow to just send the HD image, it's either got compressed and send as "image" or it sends it as a file (attachement)
