### ISSUE TITLE
Media in message.ack events

### ISSUE THREAD

**Issue by KKshitiz** [allburov/whatsapp-http-api#271]
For `message` webhook event, I'm able to get the media in this object inside the webhook payload:
```
media: {
    url: string;
    mimetype: string;
    filename?: string;
  };
```

I also want to download the media locally and get this media object while sending the messages, ie, when the `message.ack` webhook event is triggered.

Is it supported? Any ideas how to implement this?

**Comment by devlikepro** [comment]
Hi! I think what you're looking for is `message.any` event
If you specify `message.any` (instead of `message`) - you'll get webhook when the participant AND your account send a message in a chat
https://waha.devlike.pro/docs/how-to/webhooks/#messageany
This one should have `media` with the URL as well.

Let me know if it doesn't and we'll look at this!


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by KKshitiz** [comment]
Thanks a lot! I was testing `message.any` event and it worked.
