### ISSUE TITLE
Send message in broadcast?

### ISSUE THREAD

**Issue by giovannicarella** [allburov/whatsapp-http-api#308]
Is it possible to add sending messages to broadcast lists?

This way I can avoid creating automation for mass sending of messages

**Comment by allburov** [comment]
Hi! Do you mean the same message to different numbers? 
For that just call sendText multiple times in for cycle with some delay between messages and "typing" before (otherwise it seems pretty bot-like)
https://waha.devlike.pro/docs/overview/how-to-avoid-blocking/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by giovannicarella** [comment]
Thanks,
i tried to send 160 message and work perfectly...
