### ISSUE TITLE
[Feature Request][NOWEB] - Is it possible to remove the Whatsapp session on the device when logging out?

### ISSUE THREAD

**Issue by gsoftdobrasil** [allburov/whatsapp-http-api#327]
Whenever the user disconnects (logouts) the session on the api, it would be interesting to remove the Whatsapp connection on the device to prevent this connection from becoming inactive, because when starting a new session and the user connects, the device will have another connection. As Whatsapp has a limit of 4 connections, it would be interesting to automate this.

Yours sincerely,
Gildicley Alves Pereira

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Have such request, will look at this!
https://github.com/devlikeapro/whatsapp-http-api/issues/148

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Fixed in `2024.10.9`

When a session in `WORKING` status on `POST /api/sessions/{NAME}/logout`  request it'll try to remove the device from **Connected Devices** list in the app.

https://waha.devlike.pro/docs/how-to/sessions/#logout-session

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
