### ISSUE TITLE
[Feature Request] [WEBJS] Automatically restart FAILED sessions to resume functionality.

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#355]
**Is your feature request related to a problem? Please describe.** I'm always
frustrated when session moves to FAILED state randomly and session has to be restarted and sometime we have to scan again. 

**Describe the solution you'd like**

Add a option where we can automatically restart the FAILED sessions.

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Fixed in 2024.5.14!
In case of any FAILED for WEBJS it'll be restarted after 2 seconds delay.

> sometime we have to scan again.

If it doesn't help help with - let us know, may be there's some issues or reconnections from WA side

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
