### ISSUE TITLE
error after the qr code scan , before the authentication 

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#46]
engine : default engine
waha details : 
```
{
  "version": "2022.12.11",
  "tier": "CORE"
}
```

how to replicate : simple, start a session and scan a qr code, wait a few seconds and bam, red stuff on the console.

more details:

error that I get when I call the screenshot endpoint after scanning the qr code
```
{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}
```

error on the console:
```
ERROR [WhatsappSession - default] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
```

possible solution : 
https://github.com/pedroslopez/whatsapp-web.js/issues/1913#issuecomment-1379831986

**Comment by allburov** [comment]
Thank you for providing the quick solution for the issue!
Fixed in both core and plus latest versions - `2023.1.15`

**Comment by behind24proxies** [comment]
thanks ❤️

**Comment by MasamioNakada** [comment]
I have the same issue, with the version 2022-12-11, the problem is that I have de plus version, and if I drop the container, I will need to login again to get the latest version, but  my password expires.. :c  What could I do?

`[Nest] 21  - 01/17/2023, 3:39:27 PM   ERROR [WhatsappSession - Masami] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76`

**Comment by behind24proxies** [comment]
he fixed it, update the docker image
