### ISSUE TITLE
[BUG][NOWEB] -  FAILED error will appear after logging out on whatsapp, which cannot be solved. You can only delete it and create it again.

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#480]
NOWEB 2024.8.1版本
![1723019710418](https://github.com/user-attachments/assets/9f21d4f7-db2a-44f2-9c31-1932d9cb4cdd)
FAILED error will appear after logging out on whatsapp, which cannot be solved. You can only delete it and create it again.

**Comment by devlikepro** [comment]
Yes, that's the current behavior - we don't restart it because it could be some temp issue.

We'll add /restart session and v2 API for controlling sessions (and better UI for Dashboard) in `2024.9`, as well as track logouts better and asking for a QR :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> Yes, that's the current behavior - we don't restart it because it could be some temp issue.
> 
> We'll add /restart session and v2 API for controlling sessions (and better UI for Dashboard) in `2024.9`, as well as track logouts better and asking for a QR 🤞
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

OK, thank you, looking forward to the 2024.9 version

**Comment by devlikepro** [comment]
Sessions can be controlled properly now using new API in `2024.9.1`!
https://waha.devlike.pro/docs/how-to/sessions/
![image](https://github.com/user-attachments/assets/b235cb3b-7e8f-41e1-9eb7-cfb73b396f88)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
