### ISSUE TITLE
[BUG][WEBJS] - Unable to Send Poll

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#501]
I am Using this :
curl -X 'POST' \
  'http://103.199.214.72:3001/api/sendPoll' \
  -H 'accept: */*' \
  -H 'X-Api-Key: 933933' \
  -H 'Content-Type: application/json' \
  -d '{
  "chatId": "918441933933@c.us",
  "poll": {
    "name": "How are you?",
    "options": [
      "Awesome!",
      "Good!",
      "Not bad!"
    ],
    "multipleAnswers": false
  },
  "session": "7891XXXX33_J1V_WHA"
}'

Getting Error :
{
  "statusCode": 422,
  "message": "The method is not implemented by the engine.",
  "error": "Unprocessable Entity"
}

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Are you using WEBJS engine? Because polls are available only in NOWEB right now
https://waha.devlike.pro/docs/engines/noweb/
![image](https://github.com/user-attachments/assets/3474fd94-a184-4d9e-857c-36ae9ec483c8)


Comment +1 in https://github.com/devlikeapro/waha/issues/189 to get a notification when it's ready in WEBJS!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
