### ISSUE TITLE
System Requirements for Running 500 Concurrent Sessions on WhatsApp API with Docker Desktop

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#512]
I have recently purchased the WhatsApp API and plan to run it on Docker Desktop. I aim to handle approximately 500 concurrent sessions at the same time.

Could you please provide the following details regarding the required system configuration?

Processor Requirements: What type of processor (number of cores, GHz) is necessary to support 500 concurrent sessions efficiently?

Threads: How many threads should the system be able to handle for optimal performance with 500 sessions?

RAM: What is the minimum and recommended amount of RAM required for managing 500 sessions simultaneously?

Storage: How much disk space is required? Is there an advantage to using SSD over HDD for this setup?

Operating System: Are there any specific OS requirements or recommendations for running Docker Desktop with the WhatsApp API to support 500 sessions?

Your guidance will be highly appreciated to ensure that the setup can handle the desired load effectively.

Thank you.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi chatgpt, looking for John?

@smihheemmaanntt 
Here's approximate estimations based on common behaviour and depending on engine you're using
https://waha.devlike.pro/docs/overview/faq/#system-requirements

Keep in mind that it's average value, so you need to measure the requirements based on your accounts and behaviour.

> How many threads should the system be able to handle for optimal performance with 500 sessions?

Because it's nodejs it consume a single thread. It can handle 500 sessions in a single continer (for NOWEB engine), but we recommend distributing the payload across multiple containers this way 
https://waha.devlike.pro/blog/waha-scaling-how-to-handle-500-sessions/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@smihheemmaanntt let me know if there's any specific questions about it! 



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
