### ISSUE TITLE
[BUG][WEBJS] - Authentication information lost

### ISSUE THREAD

**Issue by TimousFly** [allburov/whatsapp-http-api#584]
For a new WhatsApp account authenticated by scanning the QR code, after restarting, the authentication information is lost and you need to scan the QR code to log in again.

**Comment by devlikepro** [comment]
Hi! Too broad description, could you explain your setup?
Have you followed the guide to install? 
https://waha.devlike.pro/docs/how-to/install/

Remember to wait at least 1 minute in order to give chrome(ium) and webjs chance to save all data. If you restart server early - it got corrupted and it will require re-pairing

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
How many sessions do you have? 
File storage or mongodb?
What WAHA version do you use (http://localhost:3000/api/version)?
may be there's anything in logs?  

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TimousFly** [comment]
> Hi! Too broad description, could you explain your setup? Have you followed the guide to install? https://waha.devlike.pro/docs/how-to/install/
> 
> Remember to wait at least 1 minute in order to give chrome(ium) and webjs chance to save all data. If you restart server early - it got corrupted and it will require re-pairing
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Problems that occur when restarting within a short period of time after startup
