### ISSUE TITLE
Does buying WAHA Plus mean I have to buy it again every month to use it?

### ISSUE THREAD

**Issue by mehmetcoskun** [allburov/whatsapp-http-api#59]
### Discussed in https://github.com/devlikeapro/whatsapp-http-api/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **mehmetcoskun** February 13, 2023</sup>
Does buying WAHA Plus mean I have to buy it again every month to use it? the instructions on the website say this but I want to make sure :)

Thank You.</div>

**Comment by allburov** [comment]
Hi! 
First of all, we don't sell waha, it's not a purchase, it's a donation. Almost everything for a small bot WAHA provides in Core version, Plus is just our way to say Thank you!

No, you don't have, the installed version has no license check.

But time to time WhatsApp adds some backward incompatible changes, so you'll need to update WAHA in order to make it work again.
You can assume that it happens time to time, like every 3-6 months - here you'll have to donate one lore time to get new api keys.
