### ISSUE TITLE
[NOTE] remember to protect your endpoints 

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#624]
Hi, a quick search of "WAHA" on shordan exposes a ton of whatsapp instances running. Remember to protect your endpoints.

**Comment by devlikepro** [comment]
Hi! Yes, thank you for reminder!
For Plus we have built-in security features
https://waha.devlike.pro/docs/how-to/security/
1. You can protect swagger with `WHATSAPP_SWAGGER_USERNAME` and `WHATSAPP_SWAGGER_PASSWORD` environment variables
2.You can protect dashboard with `WAHA_DASHBOARD_USERNAME` and `WAHA_DASHBOARD_PASSWORD`
3. **the most important part** (because actually previous two just hide static html, which is not super secret anyway) you **must** protect your api with `WHATSAPP_API_KEY` environment variables

If you follow the latest [Installation guide](https://waha.devlike.pro/docs/how-to/install/) it has `.env` file with the variables mentioned above.



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
