### ISSUE TITLE
[BUG][WEBJS] - Http Error 429

### ISSUE THREAD

**Issue by Abh7791** [allburov/whatsapp-http-api#633]
After update getting error Http Error 429. 
Screen Shot attached. 
Kindly Help . Cannot log in now
![image](https://github.com/user-attachments/assets/12bdc927-4d90-490c-a31e-f50a0517b080)

**Comment by devlikepro** [comment]
Hi! Fixed in `2024.11.4` :crossed_fingers: 
If that doesn't work - could you provide run a session with "debug: enabled" flag and provide full logs :pray: You can send it in waha@devlike.pro 

📢 **WORKAROUND** - if you see the error - usually switching to proxy help
https://waha.devlike.pro/docs/how-to/proxy/
Even [proxy6](https://waha.devlike.pro/docs/how-to/proxy/#proxy6) with like $2/mo works as a quick fix

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
